# Generated by Django 4.2.26 on 2026-06-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=160)),
                ("description", models.TextField()),
                ("cta_text", models.CharField(default="GET SPECS", max_length=40)),
                (
                    "solution_id",
                    models.CharField(
                        help_text="Used by templates and CSS. Change carefully after publishing.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("illustration_type", models.CharField(blank=True, max_length=80)),
                ("primary_image_path", models.CharField(blank=True, max_length=255)),
                ("visual_caption", models.CharField(blank=True, max_length=120)),
                ("show_visual_nav", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=40)),
                ("message", models.TextField()),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[("contact", "Contact"), ("specs", "Specs")],
                        default="contact",
                        max_length=20,
                    ),
                ),
                (
                    "requested_solution_slug",
                    models.SlugField(blank=True, max_length=120),
                ),
                ("source_path", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("contacted", "Contacted"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_solution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="website.solution",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "contact inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SolutionVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("caption", models.CharField(blank=True, max_length=160)),
                ("image_path", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visuals",
                        to="website.solution",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
                "unique_together": {("solution", "image_path")},
            },
        ),
    ]
