# Generated by Django 4.2.26 on 2026-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(default="main", max_length=40, unique=True)),
                (
                    "browser_title",
                    models.CharField(
                        default="Trusted Defense Solutions", max_length=120
                    ),
                ),
                ("hero_title", models.CharField(max_length=180)),
                ("hero_description", models.TextField()),
                ("cta_text", models.CharField(default="OUR SOLUTIONS", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "home page content",
                "verbose_name_plural": "home page content",
            },
        ),
    ]
