# Generated by Django 4.2.26 on 2026-06-04 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_homepagecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("website.contactinquiry",),
        ),
        migrations.CreateModel(
            name="SpecsRequest",
            fields=[],
            options={
                "verbose_name": "specs request",
                "verbose_name_plural": "specs requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("website.contactinquiry",),
        ),
    ]
