# Generated by Django 4.2.26 on 2026-06-05 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_solution_primary_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="logo_image",
            field=models.FileField(blank=True, upload_to="solution-logo/"),
        ),
        migrations.AddField(
            model_name="solution",
            name="logo_image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
