# Generated by Django 4.2.26 on 2026-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_solution_logo_image_solution_logo_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.FileField(blank=True, upload_to="site-branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.FileField(blank=True, upload_to="site-branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
