# Generated by Django 4.2.26 on 2026-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_sitesettings_favicon_sitesettings_favicon_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(
                default="ALL RIGHTS RESERVED 2026 © VANGUARD TECHNOLOGIES",
                max_length=160,
            ),
        ),
    ]
