# Generated by Django 4.2.26 on 2026-06-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_sitesettings_footer_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="social_image",
            field=models.FileField(blank=True, upload_to="site-branding/"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="social_image_path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
